### ISSUE TITLE
Search box is not working.

### ISSUE THREAD

**Issue by jmbertoncelli** [CermakM/jupyter-datatables#1]
Hello, the search input field is not working.  When I do input a string then the cell switch in Markdown mode. Any idea?

**Comment by CermakM** [comment]
Hello and thank you for trying out jupyter-datatables!

You are right, I noticed that the search box collides with Jupyter keybord shortcuts or other extensions (for example vim-plugin). I'll do my best to make sure this is fixed in 0.3.0.

**Comment by CermakM** [comment]
The [jupyter-datatables 0.2.2](https://pypi.org/project/jupyter-datatables/) Should contain the fix for the Search box, please, check it out! :) 

Relevant commit: https://github.com/CermakM/jupyter-datatables/commit/91e25ac999a61772aefd8baa595ffa92152806ca
