### ISSUE TITLE
How does work "categorical"?

### ISSUE THREAD

**Issue by jmbertoncelli** [CermakM/jupyter-datatables#2]
How does work "categorical"?

**Comment by CermakM** [comment]
Hello @jmbertoncelli,

Thanks for giving this a shot! The categorical data preview should be available in `0.2.0`.

**Comment by CermakM** [comment]
The feature has been introduced by https://github.com/CermakM/jupyter-datatables/commit/c138b81f5d47a599c02e5b4c9deb3df04fb49436

**Comment by CermakM** [comment]
Closing this issue as `0.2.0` is about to be released. If your problem is not solved by the release, please, re-open the issue or open a new one. Thanks!
