### ISSUE TITLE
Add a method or ability to deactivate the jupyter-datatable view

### ISSUE THREAD

**Issue by ZachariahRosenberg** [CermakM/jupyter-datatables#28]
**Is your feature request related to a problem? Please describe.**
The table views are terrific! I have found times, however, where I need to revert back to the old view without all of the graphs/sampling.

**Describe the solution you'd like**
It would be terrific if there could be a method that reverses `init_datatables_mode()`. Perhaps a method such as `jupyter_datatables.enable_datatables(True)`

**Comment by CermakM** [comment]
@ZachariahRosenberg thanks for the suggestion! Do you want give the PR a shot? :)

**Comment by ZachariahRosenberg** [comment]
Would like to @CermakM - unfortunately I'm blocked by the Conda Env issue #26 

Thanks!
