### ISSUE TITLE
Cannot install, `requirements.txt` missing from sdist

### ISSUE THREAD

**Issue by toddrme2178** [CermakM/jupyter-datatables#5]
I am trying to install from the sdist, and I get the following error:

```
Traceback (most recent call last):
  File "setup.py", line 17, in <module>
    REQUIREMENTS: list = Path(HERE, 'requirements.txt').read_text().splitlines()
  File "/usr/lib64/python3.7/pathlib.py", line 1189, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib64/python3.7/pathlib.py", line 1176, in open
    opener=self._opener)
  File "/usr/lib64/python3.7/pathlib.py", line 1030, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
```

Looking at the archive, I notice that `setup.py` tries to load the `requirements.txt` file, but this file is missing from the archive.

**Comment by CermakM** [comment]
The requirements.txt were indeed missing from the sdist, along with the Pipfile and static css and js files (as mentioned in #3). Thanks for pointing that out.

Please, check out the [v0.2.1](https://pypi.org/project/jupyter-datatables/) and see if the issue is solved.
